[env:adafruit_feather_esp32_v2]
platform = espressif32@7.0.1
board = adafruit_feather_esp32_v2
framework = arduino
board_build.partitions = partitions.csv

upload_port = /dev/cu.usbserial-59680111041
upload_speed = 230400
monitor_port = /dev/cu.usbserial-59680111041
monitor_speed = 115200
